name: Debug build

on:
  push:
    branches:
      - main-next
      - dev-next
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/debug.yml'
  pull_request:
    branches:
      - main-next
      - dev-next

jobs:
  build:
    name: Debug build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get latest go version
        id: version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Cache go module
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
      - name: Add cache to Go proxy
        run: |
          version=`git rev-parse HEAD`
          mkdir build
          pushd build
          go mod init build
          go get -v github.com/sagernet/sing-box@$version
          popd
        continue-on-error: true
      - name: Run Test
        run: |
          go test -v ./...
  build_go118:
    name: Debug build (Go 1.18)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.10
      - name: Cache go module
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
          key: go118-${{ hashFiles('**/go.sum') }}
      - name: Run Test
        run: make
  cross:
    strategy:
      matrix:
        include:
          # windows
          - name: windows-amd64
            goos: windows
            goarch: amd64
            goamd64: v1
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: windows-amd64-v3
            goos: windows
            goarch: amd64
            goamd64: v3
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: windows-386
            goos: windows
            goarch: 386
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: windows-arm64
            goos: windows
            goarch: arm64
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: windows-arm32v7
            goos: windows
            goarch: arm
            goarm: 7
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          
          # linux
          - name: linux-amd64
            goos: linux
            goarch: amd64
            goamd64: v1
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-amd64-v3
            goos: linux
            goarch: amd64
            goamd64: v3
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-386
            goos: linux
            goarch: 386
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-arm64
            goos: linux
            goarch: arm64
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-armv5
            goos: linux
            goarch: arm
            goarm: 5
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-armv6
            goos: linux
            goarch: arm
            goarm: 6
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-armv7
            goos: linux
            goarch: arm
            goarm: 7
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-mips-softfloat
            goos: linux
            goarch: mips
            gomips: softfloat
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-mips-hardfloat
            goos: linux
            goarch: mips
            gomips: hardfloat
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-mipsel-softfloat
            goos: linux
            goarch: mipsle
            gomips: softfloat
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-mipsel-hardfloat
            goos: linux
            goarch: mipsle
            gomips: hardfloat
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-mips64
            goos: linux
            goarch: mips64
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-mips64el
            goos: linux
            goarch: mips64le
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: linux-s390x
            goos: linux
            goarch: s390x
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          # darwin
          - name: darwin-amd64
            goos: darwin
            goarch: amd64
            goamd64: v1
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: darwin-amd64-v3
            goos: darwin
            goarch: amd64
            goamd64: v3
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: darwin-arm64
            goos: darwin
            goarch: arm64
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          # freebsd
          - name: freebsd-amd64
            goos: freebsd
            goarch: amd64
            goamd64: v1
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: freebsd-amd64-v3
            goos: freebsd
            goarch: amd64
            goamd64: v3
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: freebsd-386
            goos: freebsd
            goarch: 386
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
          - name: freebsd-arm64
            goos: freebsd
            goarch: arm64
            CGO_ENABLED: 0
            TAGS: with_clash_api,with_quic
            
          # Android
          - name: android-armv7
            goos: android
            goarch: arm
            goarm: 7
            CGO_ENABLED: 1
            CC: /opt/hostedtoolcache/ndk/r21e/x64/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang
            TAGS: with_clash_api,with_quic,with_lwip

      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      GOARM: ${{ matrix.goarm }}
      GOMIPS: ${{ matrix.gomips }}
      CGO_ENABLED: ${{ matrix.CGO_ENABLED }}
      CC: ${{ matrix.CC }}
      TAGS: ${{ matrix.TAGS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get latest go version
        id: version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Cache go module
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
      - name: Setup Android NDK
        if: |
          matrix.goos == 'android' && matrix.goarch == 'arm' && matrix.goarm == '7'
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          add-to-path: false
      - name: Build
        id: build
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sing-box-${{ matrix.name }}
          path: sing-box*
